"""محتوى طبي تعليمي أصلي بالإنجليزية مع شرح عربي.

لا يتضمن بيانات مرضى أو نصيحة فردية. تمت مراجعة المصادر في 2026.
"""

from __future__ import annotations

import json
from typing import Any

_CONTENT_JSON = (
    '{"diabetes":{"clinical_pearl_ar":"قد يكون الشخص المصاب بالنوع الثاني بلا شعور بالمرض. يقدّر A1C متوس'
    'ط الغلوكوز خلال نحو 2–3 أشهر سابقة، بينما تعكس اختبارات الصيام وتحمل الغلوكوز والعشوائي حالات مختلفة'
    '؛ وقد لا تتطابق النتائج، لذا يهم تأكيد التشخيص سريرياً.","clinical_pearl_en":"A normal-feeling perso'
    'n can still have type 2 diabetes. A1C estimates average glucose over roughly the previous 2–3 months'
    ', while fasting, oral-glucose-tolerance, and random tests reflect different glucose states; results '
    'may not agree, so clinical confirmation matters.","diagnosis_ar":"يُشخَّص السكري بمعايير مخبرية تخص '
    'A1C أو غلوكوز البلازما. لدى غير الحوامل، تشمل المعايير: A1C بنسبة 6.5% أو أكثر، أو سكر صائم 126 mg/d'
    'L (7.0 mmol/L) أو أكثر، أو سكر ساعتين 200 mg/dL (11.1 mmol/L) أو أكثر بعد اختبار تحمّل 75 غ من الغلو'
    'كوز، أو سكر عشوائي 200 mg/dL مع أعراض نموذجية أو أزمة فرط سكر. عند غياب فرط سكر واضح، يلزم تأكيد الن'
    'تيجة.","diagnosis_en":"Diagnosis uses laboratory A1C or plasma-glucose criteria. In nonpregnant adul'
    'ts, diabetes is indicated by A1C ≥6.5%, fasting plasma glucose ≥126 mg/dL (7.0 mmol/L), 2-hour gluco'
    'se ≥200 mg/dL (11.1 mmol/L) during a 75-g oral glucose-tolerance test, or random glucose ≥200 mg/dL '
    'with classic symptoms or a hyperglycemic crisis. Without unequivocal hyperglycemia, confirmatory tes'
    'ting is required.","explanation_ar":"داء السكري مجموعة من الاضطرابات المزمنة يحدث فيها نقص الإنسولين'
    ' أو ضعف الاستجابة له، مما يرفع سكر الدم. تشمل الأنواع الرئيسية النوع الأول والثاني وسكري الحمل وأنوا'
    'عاً أخرى محددة. قد يؤدي ارتفاع السكر المستمر إلى أذى العينين والكلى والأعصاب والقلب والأوعية، ويمكن '
    'للرعاية المبكرة منع المضاعفات أو تأخيرها.","id":"diabetes","key_points_ar":["يرتبط النوع الأول بنقص '
    'شديد في الإنسولين؛ أما النوع الثاني فعادةً فيجمع مقاومة الإنسولين مع نقص نسبي فيه.","قد يبقى النوع ا'
    'لثاني بلا أعراض سنوات، لذلك يُعد الفحص المبني على عوامل الخطورة مهماً.","الغذاء الصحي والنشاط المنتظ'
    'م وإدارة الوزن وتجنب التبغ قد تمنع أو تؤخر كثيراً من حالات النوع الثاني.","تشمل الرعاية طويلة الأمد '
    'ضبط السكر وفحص الكلى والعينين والقدمين والأعصاب والقلب والأوعية."],"key_points_en":["Type 1 diabetes'
    ' involves severe insulin deficiency; type 2 commonly combines insulin resistance with relative insul'
    'in deficiency.","Type 2 diabetes may be silent for years, so risk-based screening matters.","Healthy'
    ' eating, regular activity, weight management, and avoiding tobacco can prevent or delay many cases o'
    'f type 2 diabetes.","Long-term care includes glucose management plus screening for kidney, eye, foot'
    ', nerve, and cardiovascular complications."],"management_ar":"تُفصَّل الخطة حسب الحالة، وتشمل تثقيف '
    'السكري والغذاء الصحي والنشاط البدني ومراقبة الغلوكوز عند الحاجة وأدوية يختارها الطبيب. يحتاج النوع ا'
    'لأول إلى الإنسولين للبقاء. وقد يجمع علاج النوع الثاني بين نمط الحياة والأدوية، مع مراعاة السكر وأمرا'
    'ض القلب أو الكلى وخطر هبوطه والتفضيلات وإمكانية الحصول على العلاج. تساعد الفحوص الدورية على كشف المض'
    'اعفات مبكراً.","management_en":"Management is individualized and combines diabetes education, health'
    'y eating, physical activity, glucose monitoring when indicated, and clinician-selected medicines. Ty'
    'pe 1 diabetes requires insulin for survival. Type 2 treatment may use lifestyle measures and medicin'
    'es, with choices shaped by glucose, cardiovascular or kidney disease, hypoglycemia risk, preferences'
    ', and access. Regular checks help detect complications early.","mcq":{"correct_index":0,"explanation'
    '_ar":"الإجابة الصحيحة هي الخيار الأول: A1C بنسبة 6.5% أو أكثر يطابق معيار تشخيص السكري. أما القيم ال'
    'أخرى المذكورة فلا تبلغ حدود التشخيص الخاصة بالاختبارات المعروضة. وعند غياب فرط سكر واضح، يلزم تأكيد '
    'النتيجة باختبار مناسب.","options_en":["A1C of 6.5%","Fasting plasma glucose of 115 mg/dL","2-hour or'
    'al-glucose-tolerance result of 135 mg/dL","A1C of 5.6%"],"question_en":"Which result meets an ADA 20'
    '26 laboratory criterion for diabetes in a nonpregnant adult?"},"name_ar":"داء السكري","name_en":"Dia'
    'betes Mellitus","overview_en":"Diabetes mellitus is a group of chronic disorders in which insulin is'
    ' insufficient or not used effectively, causing hyperglycemia. Major categories include type 1, type '
    '2, gestational, and other specific types. Persistent hyperglycemia can damage the eyes, kidneys, ner'
    'ves, heart, and blood vessels, but timely care can prevent or delay complications.","red_flags_ar":['
    '"قد تشير الحماض الكيتوني إلى عطش شديد وتبوّل متكرر مع غثيان أو قيء أو ألم بطني أو رائحة نفس فاكهية أ'
    'و تعب شديد.","من علامات الطوارئ التنفس السريع أو العميق، صعوبة التنفس، الارتباك، أو عدم القدرة على ا'
    'لاحتفاظ بالسوائل.","تستلزم هذه العلامات التثقيفية تقييماً إسعافياً عاجلاً؛ لا تؤخر طلب المساعدة بسبب'
    ' نصيحة عبر الإنترنت."],"red_flags_en":["Possible DKA: very thirsty with frequent urination, nausea o'
    'r vomiting, stomach pain, fruity breath, or unusual tiredness.","Emergency signs include fast or dee'
    'p breathing, trouble breathing, confusion, or inability to keep fluids down.","These educational war'
    'ning signs require urgent emergency assessment; do not delay for online advice."],"references":[{"pu'
    'blisher":"American Diabetes Association Professional Practice Committee","title":"2. Diagnosis and C'
    'lassification of Diabetes: Standards of Care in Diabetes—2026","url":"https://diabetesjournals.org/c'
    'are/article/49/Supplement_1/S27/163926/2-Diagnosis-and-Classification-of-Diabetes","year":"2026"},{"'
    'publisher":"World Health Organization","title":"Diabetes","url":"https://www.who.int/news-room/fact-'
    'sheets/detail/diabetes","year":"2024"},{"publisher":"Centers for Disease Control and Prevention","ti'
    'tle":"Diabetic Ketoacidosis","url":"https://www.cdc.gov/diabetes/about/diabetic-ketoacidosis.html","'
    'year":"2024"}],"image_path":"static/medical_topics/diabetes.jpg"},"asthma":{"clinical_pearl_ar":"غيا'
    'ب الأعراض لفترة لا ينفي الربو؛ فالتشخيص يعتمد على نمط متغيّر متوافق مع المرض، مع إثبات تغيّر محدودية'
    ' تدفق الزفير عندما يكون ذلك ممكناً.","clinical_pearl_en":"A normal symptom-free interval does not ex'
    'clude asthma: the diagnosis depends on a compatible variable pattern plus evidence of variable expir'
    'atory airflow limitation when feasible.","diagnosis_ar":"يعتمد التشخيص على نمط الأعراض والتاريخ المر'
    'ضي والفحص، مع اختبارات موضوعية عند الحاجة. يقيس قياس التنفس تدفق الهواء وقد يُقارن قبل موسّع الشعب و'
    'بعده؛ وقد تفيد ذروة الجريان أو فحوص FeNO في حالات مختارة. يجب أن يقيّم الطبيب أسباباً أخرى لأعراض مش'
    'ابهة.","diagnosis_en":"Diagnosis uses the symptom pattern, medical history, examination, and objecti'
    've testing when appropriate. Spirometry measures airflow and may be compared before and after a bron'
    'chodilator; peak-flow or FeNO testing can support assessment in selected cases. Other causes of simi'
    'lar symptoms should be considered by a clinician.","explanation_ar":"الربو مرض مزمن يصيب الرئتين؛ يؤ'
    'دي التهاب وتضيّق الشعب الهوائية إلى صفير وضيق نفس وضيق بالصدر أو سعال متغيّر. قد تثير النوبات العدوى'
    ' أو الدخان أو مسببات الحساسية أو التلوث أو الجهد. هذا محتوى تعليمي عام وليس نصيحة شخصية.","id":"asth'
    'ma","key_points_ar":["تتغير الأعراض مع الوقت وقد تسوء ليلاً أو صباحاً أو مع الجهد أو بعد محفزات معين'
    'ة.","تحدث النوبة عندما يقل تدفق الهواء بسبب التورم وتقبض العضلات والمخاط.","يصيب الربو الأطفال والبا'
    'لغين؛ وتختلف المحفزات بين الأشخاص وقد تتبدل مع الزمن.","تساعد خطة مكتوبة للربو على اكتشاف التدهور وم'
    'عرفة خطوات التصعيد."],"key_points_en":["Symptoms vary over time and may worsen at night, early morni'
    'ng, with exercise, or after triggers.","An attack occurs when airway swelling, muscle tightening, an'
    'd mucus reduce airflow.","Asthma can affect children and adults; triggers differ between people and '
    'may change over time.","A written asthma action plan supports recognition of worsening symptoms and '
    'planned escalation."],"management_ar":"تُحدَّد الخطة بشكل فردي وتُراجع بانتظام. قد تشمل علاجاً مُسيط'
    'راً مضاداً للالتهاب، وخطة دواء مُسعف، وتقليل المحفزات، وتعليم طريقة استخدام البخاخ، والمتابعة، وخطة '
    'عمل مكتوبة. تساعد الكورتيكوستيرويدات المستنشقة على ضبط التهاب الشعب؛ ويعتمد الاختيار على العمر ونمط '
    'الأعراض والخطر والاستجابة والإرشادات المحلية. لا تغيّر العلاج الموصوف دون استشارة مختص.","management'
    '_en":"Management is individualized and reviewed regularly. It may include an anti-inflammatory contr'
    'oller, a reliever strategy, trigger reduction, inhaler-technique education, monitoring, and a writte'
    'n action plan. Inhaled corticosteroids help control airway inflammation; treatment choice depends on'
    ' age, symptom pattern, risk, response, and local guidance. Do not change prescribed treatment withou'
    't professional advice.","mcq":{"correct_index":0,"explanation_ar":"الإجابة الصحيحة هي قياس التنفس (S'
    'pirometry)، إذ يقيس كمية وسرعة الهواء الزفير ويساعد على تقييم محدودية تدفق الهواء. أما الاختبارات ال'
    'أخرى فقد تُستخدم لأسباب أو تشخيصات مختلفة وليست الاختبار الوظيفي الأساسي للربو.","options_en":["Spir'
    'ometry","Chest X-ray","Electrocardiogram","Complete blood count"],"question_en":"Which test most dir'
    'ectly measures airflow during an initial objective assessment for suspected asthma?"},"name_ar":"الر'
    'بو","name_en":"Asthma","overview_en":"Asthma is a chronic lung disease in which airway inflammation '
    'and narrowing cause variable wheeze, breathlessness, chest tightness, or cough. Symptoms may flare a'
    'fter triggers such as infections, smoke, allergens, pollution, or exercise. This is public education'
    ', not individualized medical advice.","red_flags_ar":["ضيق النفس الشديد أو المتفاقم سريعاً علامة تست'
    'دعي المساعدة الطارئة.","اطلب مساعدة عاجلة إذا لم يفد الدواء المُسعف أو منعت الأعراض النشاط المعتاد."'
    ',"إذا استمر التدهور وتعذر الوصول إلى الطبيب، فقد تلزم رعاية طارئة في المستشفى."],"red_flags_en":["Se'
    'vere or rapidly worsening trouble breathing is an emergency warning sign.","Seek urgent help if the '
    'reliever does not help or symptoms prevent usual activities.","If worsening symptoms persist and a c'
    'linician cannot be reached, emergency hospital care may be needed."],"references":[{"publisher":"Glo'
    'bal Initiative for Asthma (GINA)","title":"Global Strategy for Asthma Management and Prevention: 202'
    '6 Strategy Report","url":"https://ginasthma.org/2026-gina-strategy-report/","year":"2026"},{"publish'
    'er":"Centers for Disease Control and Prevention (CDC)","title":"About Asthma","url":"https://www.cdc'
    '.gov/asthma/about/index.html","year":"2026"},{"publisher":"National Heart, Lung, and Blood Institute'
    ' (NHLBI)","title":"2020 Focused Updates to the Asthma Management Guidelines","url":"https://www.nhlb'
    'i.nih.gov/health-topics/asthma-management-guidelines-2020-updates","year":"2020"}],"image_path":"sta'
    'tic/medical_topics/asthma.jpg"},"hypertension":{"clinical_pearl_ar":"قد يكون الشخص بخير ظاهريًا رغم '
    'إصابته بارتفاع الضغط. القياسات الدقيقة المتكررة أهم من الأعراض، وضبط الضغط يقلل خطر أمراض القلب والس'
    'كتة الدماغية وتلف الكلى.","clinical_pearl_en":"A normal-feeling person can still have hypertension. '
    'Repeated, accurate measurements are more informative than symptoms, and controlling pressure reduces'
    ' the risk of heart disease, stroke, and kidney damage.","diagnosis_ar":"يتطلب التشخيص قياسات صحيحة و'
    'متكررة وتفسيرًا سريريًا. تصف منظمة الصحة العالمية ارتفاع الضغط بأنه ضغط انقباضي 140 ملم زئبق أو أكثر'
    ' و/أو انبساطي 90 أو أكثر في يومين مختلفين. أما إرشاد AHA/ACC لعام 2025 فيستخدم حدًا أقل لارتفاع الضغ'
    'ط هو 130/80؛ لذلك يهمّ الإرشاد المطبق والخطر القلبي الوعائي الكلي.","diagnosis_en":"Diagnosis requir'
    'es correctly performed, repeated measurements and clinical interpretation. WHO describes hypertensio'
    'n as systolic pressure of 140 mmHg or higher and/or diastolic pressure of 90 mmHg or higher on two d'
    'ifferent days. The 2025 AHA/ACC guideline uses a lower high-BP threshold of 130/80 mmHg, so the appl'
    'icable guideline and overall cardiovascular risk matter.","explanation_ar":"ارتفاع ضغط الدم هو استمر'
    'ار ارتفاع ضغط الدم داخل الشرايين. غالبًا لا يسبب أعراضًا واضحة، لكنه قد يضر القلب والدماغ والكليتين '
    'والعينين مع الوقت. الطريقة الموثوقة لاكتشافه هي قياس الضغط بصورة صحيحة، وتقييم القراءات المتكررة لدى'
    ' مختص. هذا محتوى تثقيفي عام وليس نصيحة شخصية.","id":"hypertension","key_points_ar":["غالبًا لا يسبب '
    'أعراضًا؛ والقياس هو وسيلة اكتشافه.","قد يؤدي عدم ضبطه إلى أذى القلب والدماغ والكليتين والعينين.","تش'
    'مل عوامل الخطر العمر، والوراثة، وزيادة الوزن، وقلة الحركة، والملح، والتبغ، والكحول.","تساعد تغييرات '
    'نمط الحياة، وقد يحتاج بعض الأشخاص إلى أدوية يصفها المختص."],"key_points_en":["It is often silent; me'
    'asurement, not symptoms, detects it.","Uncontrolled pressure can harm the heart, brain, kidneys, and'
    ' eyes.","Risk factors include age, family history, excess weight, inactivity, high salt, tobacco, an'
    'd alcohol.","Lifestyle changes help; some people also need clinician-prescribed medicines."],"manage'
    'ment_ar":"يحدد المختص الخطة بما يناسب الحالة. تشمل الأساسيات نمطًا غذائيًا صحيًا أقل ملحًا، والنشاط '
    'البدني المنتظم، وتجنب التبغ، والاعتدال في الكحول، والحفاظ على وزن صحي، وإدارة التوتر، والمتابعة بالق'
    'ياس. قد يحتاج بعض الأشخاص إلى أدوية، وتُستخدم حسب الوصفة؛ لا تُشارك الدواء ولا توقفه دون توجيه طبي."'
    ',"management_en":"Management is individualized by a healthcare professional. Common foundations are '
    'a healthier, lower-salt eating pattern; regular physical activity; avoiding tobacco; moderating alco'
    'hol; healthy weight; stress management; and follow-up measurements. Some people need antihypertensiv'
    'e medicines, taken exactly as prescribed; do not share or stop them without clinical guidance.","mcq'
    '":{"correct_index":1,"explanation_ar":"الإجابة الصحيحة هي الخيار الثاني: غالبًا لا يسبب ارتفاع الضغط'
    ' أعراضًا، لذلك يلزم القياس الصحيح والمتكرر وتقييم المختص. لا تكفي الأعراض وحدها، ولا تثبت قراءة واحد'
    'ة دائمًا تشخيصًا دائمًا.","options_en":["It is diagnosed from symptoms alone.","It often has no symp'
    'toms, so blood-pressure measurement is essential.","One high reading always confirms permanent hyper'
    'tension.","Lifestyle changes never affect blood pressure."],"question_en":"Which statement best desc'
    'ribes hypertension?"},"name_ar":"ارتفاع ضغط الدم","name_en":"Hypertension","overview_en":"Hypertensi'
    'on is persistently elevated pressure in the arteries. It is common and often silent, yet over time i'
    't can damage the heart, brain, kidneys, and eyes. The only reliable way to detect it is proper blood'
    '-pressure measurement. This is general education, not individualized medical advice.","red_flags_ar"'
    ':["ارتفاع شديد في الضغط مع ألم الصدر أو صعوبة التنفس أو التشوش أو الضعف أو تغير الرؤية يستلزم إسعافً'
    'ا فوريًا.","الصداع الشديد أو الدوخة أو الغثيان أو القيء مع ضغط شديد الارتفاع علامة تستدعي رعاية عاجل'
    'ة.","لا تنتظر ظهور الأعراض إذا أوصى المختص بالتقييم الفوري بسبب قراءة مرتفعة جدًا."],"red_flags_en":'
    '["Very high BP with chest pain, breathing difficulty, confusion, weakness, or vision change requires'
    ' emergency care immediately.","Severe headache, dizziness, nausea, or vomiting with very high BP is '
    'an urgent warning sign.","Do not wait for symptoms if a clinician has advised immediate assessment f'
    'or a markedly high reading."],"references":[{"publisher":"World Health Organization","title":"Hypert'
    'ension","url":"https://www.who.int/news-room/fact-sheets/detail/hypertension","year":"2025"},{"publi'
    'sher":"American Heart Association","title":"2025 High Blood Pressure Guideline","url":"https://profe'
    'ssional.heart.org/en/science-news/2025-high-blood-pressure-guideline","year":"2025"},{"publisher":"C'
    'enters for Disease Control and Prevention","title":"About High Blood Pressure","url":"https://www.cd'
    'c.gov/high-blood-pressure/about/index.html","year":"2026"}],"image_path":"static/medical_topics/hype'
    'rtension.jpg"},"gastritis":{"clinical_pearl_ar":"إيجابية اختبار جرثومة المعدة مهمة سريريًا لأن الهدف'
    ' هو القضاء على العدوى، لا مجرد تخفيف الأعراض. وتشدد إرشادات الكلية الأمريكية لأمراض الجهاز الهضمي عل'
    'ى تأكيد زوال الجرثومة بعد العلاج وتجنب العلاج الثلاثي المعتمد على كلاريثروميسين تجريبيًا ما لم يثبت '
    'تحسس الجرثومة له.","clinical_pearl_en":"A positive H. pylori test is clinically meaningful because t'
    'reatment aims to eradicate the infection, not merely suppress symptoms. Current ACG guidance emphasi'
    'zes confirming eradication after therapy and avoiding empiric clarithromycin-based triple therapy un'
    'less susceptibility supports it.","diagnosis_ar":"يبدأ التقييم بالتاريخ المرضي والأعراض والأدوية وال'
    'فحص. قد تُستخدم اختبارات البراز أو زفير اليوريا للكشف عن جرثومة المعدة، إضافة إلى تحاليل الدم أو الب'
    'حث عن نزف هضمي. ويمكن أن يكشف تنظير الجهاز الهضمي العلوي مع أخذ خزعات حالة البطانة والسبب والمضاعفات'
    '؛ ويُختار الفحص بحسب السياق السريري.","diagnosis_en":"Evaluation begins with the history, symptoms, '
    'medicines, and examination. Clinicians may use H. pylori stool or urea-breath testing, blood tests, '
    'and tests for gastrointestinal bleeding. Upper-GI endoscopy with biopsies can inspect the lining, id'
    'entify causes, and assess complications; the appropriate test depends on the clinical context.","exp'
    'lanation_ar":"التهاب المعدة هو التهاب بطانة المعدة، بينما تشير اعتلالات المعدة إلى تضرر البطانة مع ا'
    'لتهاب قليل أو معدوم. قد لا تظهر أعراض لدى كثير من الناس. وعند ظهورها قد تشمل ألمًا أو انزعاجًا أعلى '
    'البطن، عسر الهضم، الغثيان، القيء، الانتفاخ أو الشبع المبكر. من الأسباب الشائعة جرثومة المعدة، وبعض ا'
    'لمسكنات المضادة للالتهاب، والكحول، والمرض الشديد، واضطرابات المناعة الذاتية.","id":"gastritis","key_'
    'points_ar":["تُعد جرثومة المعدة (H. pylori) السبب الأكثر شيوعًا لالتهاب المعدة.","قد تؤدي مضادات الا'
    'لتهاب غير الستيرويدية والكحول والمرض الشديد والمناعة الذاتية إلى أذية البطانة أو التهابها.","قد يغيب'
    'َت الأعراض؛ وقد يظهر ألم أعلى البطن أو الغثيان أو القيء أو الشبع المبكر.","لا يُعد الطعام سببًا رئيس'
    'يًا لمعظم حالات التهاب المعدة.","قد يسبب عدم العلاج مضاعفات مثل النزيف أو القرحة."],"key_points_en":'
    '["H. pylori is the most common cause of gastritis.","NSAIDs, alcohol, severe illness, and autoimmune'
    ' disease can also injure or inflame the stomach lining.","Symptoms may be absent; possible symptoms '
    'include upper-abdominal discomfort, nausea, vomiting, or early fullness.","Diet is not considered a '
    'major cause of most gastritis cases.","Untreated disease may contribute to complications such as ble'
    'eding or ulceration."],"management_ar":"يعتمد العلاج على السبب. تحتاج جرثومة المعدة إلى نظام علاجي م'
    'ركب يختاره الطبيب، مع تأكيد زوالها بعد العلاج باختبار مناسب. وقد يتطلب الضرر المرتبط بمضادات الالتها'
    'ب مراجعة الدواء أو تعديله بإشراف طبي. يمكن استخدام أدوية خفض الحموضة أو علاجات أخرى عند ملاءمتها. وق'
    'د تستلزم المناعة الذاتية تقييم نقص الحديد أو فيتامين B12. لا تبدأ أو توقف دواءً موصوفًا ذاتيًا.","ma'
    'nagement_en":"Management is cause-directed. H. pylori requires a clinician-selected combination regi'
    'men, and eradication should be confirmed after treatment with an accepted test. Suspected NSAID-rela'
    'ted injury may require clinician-guided review or modification of the medicine. Acid-reducing therap'
    'y or other treatment may be used when appropriate. Autoimmune disease may require assessment for iro'
    'n or vitamin B12 deficiency. Do not self-start or stop prescription medicines.","mcq":{"correct_inde'
    'x":0,"explanation_ar":"الإجابة الصحيحة هي جرثومة المعدة (Helicobacter pylori)، وهي السبب الأكثر شيوع'
    'ًا لالتهاب المعدة وفق المعهد الوطني للسكري وأمراض الجهاز الهضمي والكلى. لا تعني كل أعراض عسر الهضم و'
    'جود هذه العدوى؛ ويُحدد الاختبار والعلاج طبيًا.","options_en":["Helicobacter pylori","Candida albican'
    's","Influenza virus","Escherichia coli"],"question_en":"Which organism is identified by NIDDK as the'
    ' most common cause of gastritis?"},"name_ar":"التهاب المعدة","name_en":"Gastritis","overview_en":"Ga'
    'stritis is inflammation of the stomach lining; gastropathy means lining damage with little or no inf'
    'lammation. Many people have no symptoms. When present, symptoms may include upper-abdominal discomfo'
    'rt, indigestion, nausea, vomiting, bloating, or early fullness. Common causes include Helicobacter p'
    'ylori infection, anti-inflammatory pain medicines, alcohol, severe illness, and autoimmune disease. '
    'Educational content only—not personalized medical advice.","red_flags_ar":["اطلب رعاية إسعافية عند ق'
    'يء الدم أو مادة تشبه تفل القهوة، أو براز أسود لزج، أو ألم شديد مفاجئ بالبطن أو الصدر.","يلزم تقييم ط'
    'بي عاجل عند نقص الوزن غير المقصود، أو القيء المتكرر، أو صعوبة أو ألم البلع، أو الشبع بعد كمية قليلة '
    'جدًا.","يستدعي ألم أعلى البطن أو عسر الهضم المستمر أو المتكرر تقييمًا طبيًا، خاصة إذا ازداد سوءًا."]'
    ',"red_flags_en":["Seek emergency care for vomiting blood, vomit resembling coffee grounds, black sti'
    'cky stools, or sudden severe abdominal or chest pain.","Prompt medical assessment is warranted for u'
    'nintentional weight loss, repeated vomiting, painful or difficult swallowing, or fullness after a ve'
    'ry small meal.","Persistent or recurrent upper-abdominal pain or indigestion should be medically ass'
    'essed, especially if worsening."],"references":[{"publisher":"National Institute of Diabetes and Dig'
    'estive and Kidney Diseases (NIDDK/NIH)","title":"Gastritis & Gastropathy","url":"https://www.niddk.n'
    'ih.gov/health-information/digestive-diseases/gastritis-gastropathy","year":"n.d., accessed 2026"},{"'
    'publisher":"American College of Gastroenterology","title":"ACG Guideline on Treatment of Helicobacte'
    'r pylori: New Recommendations… Will Practice Change?","url":"https://gi.org/journals-publications/eb'
    'gi/schoenfeld_sep2024/","year":"2024"},{"publisher":"NHS","title":"Gastritis","url":"https://www.nhs'
    '.uk/conditions/gastritis/","year":"2026"}],"image_path":"static/medical_topics/gastritis.jpg"},"hypo'
    'thyroidism":{"clinical_pearl_ar":"التعب وتغير الوزن علامتان شائعتان لكنهما غير نوعيتين. تكون قراءة ا'
    'لتحاليل مع السياق السريري ومراجعة الأدوية والمكملات أدق من مطابقة الأعراض وحدها؛ فقد تُشوّه الجرعات '
    'العالية من البيوتين نتائج تحاليل الغدة.","clinical_pearl_en":"Fatigue and weight change are common b'
    'ut nonspecific. A biochemical pattern, clinical context, and medication or supplement review are mor'
    'e reliable than symptom-matching alone; high-dose biotin can distort thyroid test results.","diagnos'
    'is_ar":"لا تكفي الأعراض وحدها لتأكيد التشخيص. عند البالغين من دون اشتباه بمرض في الغدة النخامية، يُب'
    'دأ عادةً بقياس TSH، ثم يُقاس الثيروكسين الحر (FT4) إذا كان TSH مرتفعًا. عند الاشتباه بمرض نخامي، يُق'
    'اسان معًا. قد تساعد أضداد بيروكسيداز الغدة الدرقية في تقييم السبب المناعي، لكنها لا تغني عن تحاليل و'
    'ظائف الغدة.","diagnosis_en":"Symptoms alone cannot establish the diagnosis. For adults without suspe'
    'cted pituitary disease, NICE recommends starting with TSH; if it is above the reference range, measu'
    're free T4 in the same sample. When pituitary disease is suspected, measure TSH and free T4 together'
    '. Thyroid peroxidase antibodies can support evaluation of autoimmune cause, but are not a substitute'
    ' for thyroid-function tests.","explanation_ar":"قصور الغدة الدرقية يعني أن الغدة لا تنتج هرمونات كاف'
    'ية، فتتباطأ وظائف عديدة في الجسم. قد تظهر علامات مثل التعب، عدم تحمل البرد، الإمساك، جفاف الجلد، تغي'
    'ر الشعر أو انخفاض المزاج، لكنها ليست خاصة بالغدة وحدها. يُعد التهاب هاشيموتو سببًا شائعًا، وقد تحدث '
    'الحالة بعد الجراحة أو الإشعاع أو التهاب الغدة أو بسبب بعض الأدوية أو أمراض النخامى.","id":"hypothyro'
    'idism","key_points_ar":["قد تتطور الأعراض تدريجيًا وتكون خفيفة أو غير نوعية.","التهاب هاشيموتو سبب م'
    'ناعي شائع لقصور الغدة الأولي.","قد يساهم عدم العلاج في ارتفاع الكوليسترول، ونادرًا في غيبوبة الوذمة '
    'المخاطية الخطرة.","تجعل الحملَة تقييم الغدة ومتابعتها في الوقت المناسب أمرًا مهمًا."],"key_points_en'
    '":["Symptoms often develop gradually and may be mild or nonspecific.","Hashimoto disease is a freque'
    'nt autoimmune cause of primary hypothyroidism.","Untreated disease can contribute to high cholestero'
    'l and, rarely, life-threatening myxedema coma.","Pregnancy increases the importance of timely thyroi'
    'd assessment and follow-up."],"management_ar":"يُعد ليفوثيروكسين العلاج التعويضي الأول المعتاد لقصور'
    ' الغدة الأولي. يحدد المختص الخطة المناسبة؛ ولا ينبغي بدء الدواء أو إيقافه أو تغيير طريقة استعماله دو'
    'ن إشراف طبي. يُتابع TSH بعد بدء العلاج أو تغييره ثم دوريًا بعد استقرار النتيجة. استمرار الأعراض يستل'
    'زم إعادة التقييم لا زيادة العلاج تلقائيًا. الحمل أو التخطيط له يستدعي مراجعة مهنية مبكرة لأن الاحتيا'
    'جات قد تتغير.","management_en":"Levothyroxine is the recommended first-line replacement for primary '
    'hypothyroidism. Treatment is individualized; do not start, stop, or change thyroid medicine without '
    'clinical supervision. TSH is monitored after starting or changing therapy and periodically after sta'
    'bilization. Persistent symptoms require reassessment rather than automatic dose escalation. Pregnanc'
    'y or plans for pregnancy warrant prompt professional review because treatment needs may change.","mc'
    'q":{"correct_index":0,"explanation_ar":"الإجابة الصحيحة هي الخيار الأول. عند عدم الاشتباه بمرض نخامي'
    '، يبدأ التقييم بقياس TSH، ويُضاف FT4 في العينة نفسها إذا كان TSH أعلى من المجال المرجعي. لا تكفي الأ'
    'عراض وحدها، ولا يُعد FT3 أو التصوير بالموجات فوق الصوتية الاختبار الأول المعتاد لتأكيد قصور الغدة.",'
    '"options_en":["Measure TSH first, then add free T4 if TSH is above the reference range","Measure fre'
    'e T3 alone","Diagnose from fatigue and cold intolerance without blood tests","Order thyroid ultrasou'
    'nd as the initial diagnostic test"],"question_en":"In an adult with suspected primary hypothyroidism'
    ' and no concern for pituitary disease, which testing approach best follows NICE guidance?"},"name_ar'
    '":"قصور الغدة الدرقية","name_en":"Hypothyroidism","overview_en":"Hypothyroidism is reduced productio'
    'n of thyroid hormones, slowing many body processes. Common features include fatigue, cold intoleranc'
    'e, constipation, dry skin or hair changes, low mood, and slowed thinking, but symptoms overlap with '
    'many conditions. Hashimoto disease is a common cause; surgery, radiation, thyroiditis, medicines, io'
    'dine imbalance, or pituitary disease can also contribute.","red_flags_ar":["النعاس الشديد أو الارتبا'
    'ك أو انخفاض حرارة الجسم جدًا أو بطء التنفس أو بطء النبض بشكل ملحوظ قد تشير إلى غيبوبة الوذمة المخاطي'
    'ة؛ اطلب الإسعاف فورًا.","ضيق النفس الشديد حديثًا أو الإغماء أو ألم الصدر يستلزم تقييمًا إسعافيًا عاج'
    'لًا مهما كان السبب المحتمل.","أثناء الحمل، تلزم مراجعة عاجلة عند عدم علاج مرض معروف بالغدة أو تدهور '
    'الأعراض أو انقطاع العلاج."],"red_flags_en":["Extreme drowsiness, confusion, very low body temperatur'
    'e, slowed breathing, or a markedly slow heartbeat may signal myxedema coma: seek emergency care imme'
    'diately.","New severe breathing difficulty, fainting, or chest pain requires urgent emergency assess'
    'ment, regardless of the suspected cause.","During pregnancy, urgent clinical review is important if '
    'known thyroid disease is untreated, symptoms worsen, or treatment is interrupted."],"references":[{"'
    'publisher":"National Institute of Diabetes and Digestive and Kidney Diseases (NIH)","title":"Hypothy'
    'roidism (Underactive Thyroid)","url":"https://www.niddk.nih.gov/health-information/endocrine-disease'
    's/hypothyroidism","year":"n.d.; accessed 2026"},{"publisher":"National Institute for Health and Care'
    ' Excellence (NICE)","title":"Thyroid disease: assessment and management—Recommendations","url":"http'
    's://www.nice.org.uk/guidance/ng145/chapter/recommendations","year":"2019; updated 2023"},{"publisher'
    '":"NHS","title":"Underactive thyroid (hypothyroidism)","url":"https://www.nhs.uk/conditions/underact'
    'ive-thyroid-hypothyroidism/","year":"2025"}],"image_path":"static/medical_topics/hypothyroidism.jpg"'
    '}}'
)
BILINGUAL_TOPICS: dict[str, dict[str, Any]] = json.loads(_CONTENT_JSON)


def _normalize(value: object) -> str:
    """توحيد قيمة البحث من دون الاحتفاظ بها أو إرسالها إلى خدمة خارجية."""
    return " ".join(str(value or "").strip().casefold().split())


def get_bilingual_topic(value: object) -> dict[str, Any] | None:
    """العثور على بطاقة بالمعرّف أو الاسم العربي أو الإنجليزي."""
    query = _normalize(value)
    if not query:
        return None
    direct = BILINGUAL_TOPICS.get(query)
    if direct:
        return direct
    for topic in BILINGUAL_TOPICS.values():
        candidates = (_normalize(topic["name_ar"]), _normalize(topic["name_en"]))
        if query in candidates or any(query in candidate for candidate in candidates):
            return topic
    return None


def all_bilingual_topics() -> tuple[dict[str, Any], ...]:
    """إرجاع المحتوى بالترتيب التعليمي المعتمد."""
    return tuple(BILINGUAL_TOPICS.values())


def validate_bilingual_topics() -> None:
    """الفشل مبكرًا إذا كان سجل تعليمي ناقصًا أو غير صالح."""
    required = {
        "id", "name_en", "name_ar", "overview_en", "explanation_ar",
        "key_points_en", "key_points_ar", "diagnosis_en", "diagnosis_ar",
        "management_en", "management_ar", "red_flags_en", "red_flags_ar",
        "clinical_pearl_en", "clinical_pearl_ar", "mcq", "references", "image_path",
    }
    for key, topic in BILINGUAL_TOPICS.items():
        missing = required.difference(topic)
        if missing:
            raise ValueError(f"Incomplete bilingual topic: {key}")
        mcq = topic["mcq"]
        if len(mcq.get("options_en", [])) != 4 or mcq.get("correct_index") not in range(4):
            raise ValueError(f"Invalid bilingual MCQ: {key}")
        references = topic.get("references", [])
        if len(references) < 2 or any(not str(item.get("url", "")).startswith("https://") for item in references):
            raise ValueError(f"Invalid references: {key}")


validate_bilingual_topics()
